# service config
service:
  chain_id: irishub
  node_rpc_addr: http://localhost:26657
  node_grpc_addr: localhost:9090
  key_path: .keys
  key_name: sp
  fee: 1iris
  key_algorithm: secp256k1

API:
  random-seed-api: http://www.random.org/cgi-bin/randbyte?nbytes=32&format=h

monitor:
  interval: 5
  prometheus_addr: localhost:8888
  provider_addr:
    - iaa1cq3xx80jym3jshlxmwnfwu840jxta032aa4jss

balance:
  threshold: 10