# service config
service:
  chain_id: irishub
  node_rpc_addr: http://localhost:26657
  node_grpc_addr: localhost:9090
  key_path: .keys
  key_name: sp
  fee: 0.4iris
  key_algorithm: secp256k1

API:
  cmc: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=43bf626f-772c-4d81-9bd4-db23a26f01d4&symbol=